fablab/urls.py
from django.urls import path

from . import views

app_name = 'fablab'
urlpatterns = [
	path('', views.index, name='index'),
	path('<int:user_id>/', views.userdetails, name='userdetail'),
	path('<int:user_id>/booking', views.booking, name='userbooking'),
	path('booking', views.BookingPage.as_view(), name='fablabbooking'),
	path('about', views.AboutFablab.as_view(), name='aboutUs'),
	path('reserve', views.BookFablab.as_view(), name='reserve'),
	path('request', views.request_booking, name='request_booking'),
	path('confirmbooking', views.ConfirmBooking.as_view(), name='confirm_booking'),
]

moneymanage/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index_mongmt'),
    path('rest/<int:guess>', views.rest),
    path('main', views.MainView.as_view()),
    path('remain/<slug:txting>', views.RestMainView.as_view()),
]

mysite/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('moneymanage/', include('moneymanage.urls')),
    path('fablab/', include('fablab.urls')),
    url(r'^admin/', admin.site.urls),
]

fablab/models.py
import datetime

from django.db import models
from django.utils import timezone

class Machines(models.Model):
    name = models.CharField(max_length=60)

    def __str__(self):
        return self.name

class Users(models.Model):
    firstName = models.CharField(max_length=60)
    surName = models.CharField(max_length=60)
    email = models.EmailField(max_length=60)
    created = models.DateTimeField(auto_now_add= True)
    bookMachine = models.ManyToManyField(Machines, through='Booking')

    def __str__(self):
        return self.firstName
    def was_added_recently(self):
        return self.created >= timezone.now() - datetime.timedelta(days=1)

class Items(models.Model):
    name = models.CharField(max_length=200)
    desc = models.CharField('Description', max_length=300)
    quantity = models.IntegerField()
    loans = models.ManyToManyField(Users, through='ItemLoan')

    def __str__(self):
        return self.itemName

class ItemLoan(models.Model):
    user = models.ForeignKey(Items, on_delete=models.CASCADE)
    item = models.ForeignKey(Users, on_delete=models.CASCADE)
    loanDate = models.DateTimeField('borrowed_on')
    returnDate = models.DateTimeField('returned_on', null=True, blank=True)

    def __str__(self):
        return str(self.user)

class Booking(models.Model):
    BOOKING_TYPE = (
        ('I', 'Individual'),
        ('G', 'Group'),
        )
    user = models.ForeignKey(Users, on_delete=models.CASCADE)
    machine = models.ForeignKey(Machines, on_delete=models.CASCADE)
    slotDate = models.DateField()
    slotStatTime = models.TimeField()
    slotEndTime = models.TimeField()
    bookingType = models.CharField(max_length=300)
    groupSize = models.IntegerField()

    def __str__(self):
        return str(self.user)

moneymanage/models.py
from django.db import models

class Catagories(models.Model):
    categ_name = models.CharField(max_length=250)
    description = models.CharField(max_length=300)
    categ_type = models.CharField('categoy type', max_length=100)

class Budget(models.Model):
    catagory = models.ForeignKey(Catagories, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=100, decimal_places=2)
    frequency = models.CharField(max_length=50)

class Transactions(models.Model):
    trans_date = models.DateTimeField("transaction date")
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.CharField(max_length=300)

fablab/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.views import View
from django.views.decorators.csrf import csrf_exempt
from django.urls import reverse

import html

from datetime import datetime, timedelta
#from django.template import loader

from .models import Users

def dumpdata(place, data) :
    retval = ""
    if len(data) > 0 :
        retval += '<p>Incoming '+place+' data:<br/>\n'
        for key, value in data.items():
            retval += html.escape(key) + '=' + html.escape(value) + '</br>\n'
        retval += '</p>\n'
    return retval

def index(request):
    users_list = Users.objects.all()
    #users_list = get_list_or_404(Users, pk!=NULL)
    #template = loader.get_template('fablab/index.html')
    context = {
        'users_list': users_list,
        }
    #return HttpResponse(template.render(context, request))
    return render(request, 'fablab/index.html', context)

def userdetails(request, user_id):
    return HttpResponse("You are looking at the details of user: %s" % user_id)

def booking(request, user_id):
    #user = Users.objects.get(pk=user_id)
    user = get_object_or_404(Users, pk=user_id)
    userBooking=user.booking_set.all()
    context = {
        'user': user,
        'userBooking':userBooking
    }
    return render(request, 'fablab/user_booking.html', context)

class BookingPage(View):
    def get(self, request):
        weekDays = []
        timeOfDay = []

        today = datetime.now().weekday() #Get today's date and the work out which day it is
        delta = timedelta(days=-today) # create the time delta that would count back to Monday
        monday = datetime.now() + delta # Adding the timedelta will bring us back to monday
        dayName = monday.date().strftime("%A")
        hour = datetime(year=datetime.now().year, month=datetime.now().month, day=datetime.now().day, hour=9, minute=0)
        for i in range(5):
            theDay = []
            delta = timedelta(days=+i)
            day = monday + delta
            dayName = day.date().strftime("%A")
            theDay.append(dayName)
            theDay.append(day)
            weekDays.append(theDay)

        for i in range(9):
            deltaTime = timedelta(hours=+1)
            timeOfDay.append(hour.time)
            hour = hour + deltaTime

        context = {
            'weekDays': weekDays,
            'dayName': dayName,
            'timeOfDay': timeOfDay,
        }

        return render(request, 'fablab/booking.html', context)


class BookFablab(View):
    @csrf_exempt
    def get(self, request):
        user = get_object_or_404(Users, pk=1)
        context = {
            'user': user,
        }
        return render(request, 'fablab/book_fablab.html', context)

def request_booking(request):
    fName = request.POST['firstName']
    lName = request.POST['lastName']
    email = request.POST['email']
    resDate = request.POST['reservationDate']
    startTime = request.POST['timeFrom']
    endTime = request.POST['timeFrom']

    try:
        user = get_object_or_404(Users, firstName=fName)


    except (KeyError, Users.DoesNotExist):
        return render(request, 'fablab/book_fablab.html')
    else:
        booking = user.booking_set.all()
        context = {
            'firstName': user.surName,
        }
        return HttpResponseRedirect(reverse('fablab:confirm_booking'))

class ConfirmBooking(View):
    def get(self, request):
        user = get_object_or_404(Users, pk=1)
        user_id = user.id
        userBooking=user.booking_set.all()
        context = {
            'userBooking': userBooking,
            'user_id' : user_id,
        }
        return render(request, 'fablab/confirm.html', context)

class AboutFablab(View):
    def get(self, request):
        context = {}
        return render(request, 'fablab/about.html', context)

moneymanage/views.py
#from django.shortcuts import render
from django.http import HttpResponse
from django.utils.html import escape
from django.views import View

def index(request):
    response = """<h1> Money Manager </h1> <p><b>Hello peeps</b>, this is monenry manager website!</p>"""
    return HttpResponse(response)

def rest(request, guess):
    response = """<html><body>

    <h1> We are in Rest</h1>
    <p>The number you chose is""" + escape(guess) + """. Are you happy with your choice?</p>

    </body></html>"""

    return HttpResponse(response)

class MainView(View):
    def get(self, request):
        response = """ <html><body>
                            <h1>This is main view!</h1>
                            <p> My first real attempt at using class for views </p>
                        </body></html>"""
        return HttpResponse(response)

class RestMainView(View):
    def get(self, request, txting):
        response = """<html><body>
                        <h1> Welcome to Text Live </h1>
                        <p> This is my second attempt at class views </p>
                        <p> This time round I am experimenting with passing strings in GET </p>
                        <p> The message you have passed to me is """ + escape(txting)+ """</p>
                    </body></html>"""
        return HttpResponse(response)

fablab/templates/fablab/about.html
{% extends "fablab/base.html" %}

{% load static %}
{% block content %}

 <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">All About Us</h1>
        <p class="lead text-muted">We are based in a School in Jerez de la Frontera. The lab is currently used manily for students of the school ...</p>
        <p>
          <a href="#" class="btn btn-primary my-2">More details</a>
          <a href="#" class="btn btn-secondary my-2">Get in touch</a>
        </p>
      </div>
    </div>
  </section>

  <div class="container">

    <!-- Three columns of text below the carousel -->
    <div class="row">
      <div class="col-lg-4">
        <img src="{% static 'fablab/gru.png' %}" alt="My image" width="250" height="250">
        <h2>Da Boss</h2>
        <p>I am the Boss, as mean as can be.</p>
        <p><a class="btn btn-secondary" href="#">View details &raquo;</a></p>
      </div><!-- /.col-lg-4 -->
      <div class="col-lg-4">
        <img src="{% static 'fablab/minion1.png' %}" alt="My image" width="250" height="250">
        <h2>Worker</h2>
        <p>I like making things that might not work.</p>
        <p><a class="btn btn-secondary" href="#">View details &raquo;</a></p>
      </div><!-- /.col-lg-4 -->
      <div class="col-lg-4">
        <img src="{% static 'fablab/minion2.png' %}" alt="My image" width="250" height="250">
        <h2>Another worker</h2>
        <p>I like making things that blow up.</p>
        <p><a class="btn btn-secondary" href="#">View details &raquo;</a></p>
      </div><!-- /.col-lg-4 -->
    </div><!-- /.row -->


    <!-- START THE FEATURETTES -->

    <hr class="featurette-divider">

{% endblock %}

fablab/templates/fablab/base.html
<!doctype html>
<html lang="en">

{% load static %}
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="Israel Goitom">
        <meta name="generator" content="">


        <!-- Bootstrap CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">

        <title>Fablab Jerez de la Frontera</title></title>
    </head>

    <body class="bg-light">
        <header>
          <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
            <div class="container-fluid">
              <a class="navbar-brand" href="{% url 'fablab:index' %}">
                  <img src="{% static 'fablab/LogoFLJEREZ.png' %}" alt="Fablab logo" width="150" height="47">
              </a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav me-auto mb-2 mb-md-0">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'fablab:index' %}">Home</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'fablab:aboutUs' %}">About</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'fablab:fablabbooking' %}">Booking</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">My Booking</a>
                  </li>
                </ul>
                <a class="gx-5" href="#">
                    <img  src="{% static 'fablab/person-circle.svg' %}" alt="userIcon" width="30" height="30">
                </a>
              </div>

            </div>
          </nav>
        </header>

            {% block content %} {% endblock %}

            <footer class="my-5 pt-5 text-muted text-center text-small">
                <p class="mb-1">&copy; Fablab Jerez Altillo School</p>
                <ul class="list-inline">
                    <li class="list-inline-item"><a href="#">Privacy</a></li>
                    <li class="list-inline-item"><a href="#">Terms</a></li>
                    <li class="list-inline-item"><a href="#">Support</a></li>
                </ul>
            </footer>


    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8" crossorigin="anonymous"></script>

   </body>
</html>

fablab/templates/fablab/book_fablab.html
{% extends "fablab/base.html" %}

{% load static %}
{% block content %}

    <div class="container">

        <div class="py-5 text-center">

            <!--- <img src="{% static 'fablab/Fab_Lab_logo.png' %}" alt="My image" width="100" height="100">
            <img class="d-block mx-auto mb-4" src="images/Fab_Lab_logo.png" alt="" > -->
          <h1><br/>Booking Page</h1>
          <p class="lead">Plese fill the form below to book a time.</p>
        </div>

          <div class="col-md-7 col-lg-8">
            <form action="{% url 'fablab:request_booking' %}" method="post" class="needs-validation" novalidate>
                {% csrf_token %}
              <div class="row g-3">
                <div class="col-sm-6">
                  <label for="firstName" class="form-label">First name</label>
                  <input type="text" name="firstName" class="form-control" id="firstName" placeholder="" value="" required>
                  <div class="invalid-feedback">
                    Valid first name is required.
                  </div>
                </div>

                <div class="col-sm-6">
                  <label for="lastName" class="form-label">Last name</label>
                  <input type="text" name="lastName" class="form-control" id="lastName" placeholder="" value="" required>
                  <div class="invalid-feedback">
                    Valid last name is required.
                  </div>
                </div>

                <div class="col-12">
                  <label for="username" class="form-label">Username</label>
                  <div class="input-group has-validation">
                    <span class="input-group-text">@</span>
                    <input type="text" name="username" class="form-control" id="username" placeholder="Username" required>
                  <div class="invalid-feedback">
                      Your username is required.
                    </div>
                  </div>
                </div>

                <div class="col-12">
                  <label for="email" class="form-label">Email <span class="text-muted">(Optional)</span></label>
                  <input type="email" name="email" class="form-control" id="email" placeholder="you@example.com">
                  <div class="invalid-feedback">
                    Please enter a valid email address for shipping updates.
                  </div>
                </div>

                <div class="col-md-5">
                  <label for="reservationDate" class="form-label">Date</label>
                  <input type="date" name="reservationDate" class="form-control" id="reservationDate">
                  <div class="invalid-feedback">
                    Please select an equipment to use.
                  </div>
                </div>

                <div class="col-md-4">
                  <label for="timeFrom" class="form-label">From</label>
                  <input type="time" name="timeFrom" class="form-control" id="timeFrom">
                  <div class="invalid-feedback">
                    Please provide a valid state.
                  </div>
                </div>

                <div class="col-md-3">
                  <label for="timeTo" class="form-label">To</label>
                  <input type="time" name="timeTo" class="form-control" id="timeTo">
                  <div class="invalid-feedback">
                    Zip code required.
                  </div>
                </div>
              </div>

            <div class="col-md-5">
              <label for="equipment" class="form-label">What do you need to use</label>
              <select name="equipment" class="form-select" id="equipment" required>
                <option value="">Choose...</option>
                <option>3D Printers</option>
                <option>Laser cutter</option>
                <option>CNC router machine</option>
                <option>Vinyl cutter</option>
                <option>Plotter</option>
              </select>
              <div class="invalid-feedback">
                Please select an equipment to use.
              </div>
            </div>

              <hr class="my-4">

              <div class="form-check">
                <input type="checkbox" name="termsAndConditions" class="form-check-input" id="termsAndConditions" required>
                <label class="form-check-label" for="termsAndConditions">I agree to the terms and conditions of use of Fablab Jerez</label>
                <div class="invalid-feedback">
                    You need to have read and agreed to the terms and conditions of use of Fablab Jerez.
                </div>
              </div>

              <div class="form-check">
                <input type="checkbox" name="saveinfo" class="form-check-input" id="saveinfo">
                <label class="form-check-label" for="saveinfo">Save this information for next time</label>
              </div>

              <hr class="my-4">

              <button class="w-100 btn btn-primary btn-lg" type="submit" name="requestSubmit" >Submit Request</button>
            </form>
          </div>
    </div>

{% endblock %}

fablab/templates/fablab/booking.html
{% extends "fablab/base.html" %}

{% block content %}

    <div class="container">


        <div style="height: 100px;">
            <div class="h-25 text-center"><h1>Fablab Booking </h1></div>
        </div>
        <div class= "row gx-5">
            <div class="col-2"></div>
                {% for day in weekDays %}
                    <div class="col-2 text-center bg-info text-white border-white rounded-top border">
                        <h5>{{ day.0 }} <br />
                        {{ day.1.date }}</h5>
                    </div>
                {% endfor %}
        </div>
        {% for time in timeOfDay %}
            <div class= "row gx-5">
                <div class="col-2 text-center bg-info text-white border-white rounded-left border"><h5>{{ time }}</h5></div>
                    {% for x in '12345' %}
                        <div class="col-2 text-center bg-secondary text-white border-white border">
                        </div>
                    {% endfor %}
            </div>
        {% endfor %}
    </div>

{% endblock %}

fablab/templates/fablab/confirm.html
{% extends "fablab/base.html" %}

{% block content %}

    <section class="py-5 text-center container">
        <div class="row py-lg-5">
            <div class="col-lg-6 col-md-8 mx-auto">
                <h1 class="fw-light">Booking confiremed</h1>
                <p class="lead text-muted">Make sure you have your booking code.</p>
                <p>
                    <a href="#" class="btn btn-primary my-2">Book another seeion</a>
                    <a href="{% url 'fablab:index' %}" class="btn btn-secondary my-2">Back to home page</a>
                </p>
            </div>
        </div>
    </section>

{% endblock %}

fablab/templates/fablab/index.html
{% extends "fablab/base.html" %}

{% load static %}
{% block content %}

<main>

  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">Fablab Jerez Altillo School</h1>
        <p class="lead text-muted">Where you can make your imagination a reaity!.</p>
        <p>
          <a href="#" class="btn btn-primary my-2">Book a course</a>
          <a href="#" class="btn btn-secondary my-2">Book a session</a>
        </p>
      </div>
    </div>
  </section>

  <div class="album py-5 bg-light">
    <div class="container">

      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        <div class="col">
          <div class="card shadow-sm">
            <img src="{% static 'fablab/ultimaker2.jpg' %}" alt="3D printers">
            <div class="card-body">
              <p class="card-text">Description for 3D printers.</p>
              <div class="d-flex justify-content-between align-items-center">
               <div class="btn-group">
                  <button type="button" class="btn btn btn-outline-secondary">More detail</button>
                  <button type="button" class="btn btn btn-outline-secondary">Book a machine</button>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col">
          <div class="card shadow-sm">
            <img src="{% static 'fablab/laserCutter.jpg' %}" alt="Laser cutter">
            <div class="card-body">
              <p class="card-text">Description for laser cutter.</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn btn-outline-secondary">More detail</button>
                  <button type="button" class="btn btn btn-outline-secondary">Book a machine</button>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col">
          <div class="card shadow-sm">
            <img src="{% static 'fablab/CNCrouter.jpg' %}" alt="3D printers">
            <div class="card-body">
              <p class="card-text">Description for CNC milling machine.</p>
              <div class="d-flex justify-content-between align-items-center">
               <div class="btn-group">
                  <button type="button" class="btn btn btn-outline-secondary">More detail</button>
                  <button type="button" class="btn btn btn-outline-secondary">Book a machine</button>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="col">
          <div class="card shadow-sm">
            <img src="{% static 'fablab/graphtech.jpg' %}" alt="3D printers">
            <div class="card-body">
              <p class="card-text">Description for Vinyl Cutter.</p>
              <div class="d-flex justify-content-between align-items-center">
               <div class="btn-group">
                  <button type="button" class="btn btn btn-outline-secondary">More detail</button>
                  <button type="button" class="btn btn btn-outline-secondary">Book a machine</button>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col">
          <div class="card shadow-sm">
            <img src="{% static 'fablab/Plotter.jpg' %}" alt="3D printers">
            <div class="card-body">
              <p class="card-text">Description for Plotter.</p>
              <div class="d-flex justify-content-between align-items-center">
               <div class="btn-group">
                  <button type="button" class="btn btn btn-outline-secondary">More detail</button>
                  <button type="button" class="btn btn btn-outline-secondary">Book a machine</button>
                </div>
              </div>
            </div>
          </div>
        </div>
       <div class="col">
          <div class="card shadow-sm">
            <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
            <div class="card-body">
              <p class="card-text">Description for T-Shirt Press.</p>
              <div class="d-flex justify-content-between align-items-center">
               <div class="btn-group">
                  <button type="button" class="btn btn btn-outline-secondary">More detail</button>
                  <button type="button" class="btn btn btn-outline-secondary">Book a machine</button>
                </div>
              </div>
            </div>
          </div>
        </div>

       <div class="col">
          <div class="card shadow-sm">
            <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
            <div class="card-body">
              <p class="card-text">Description for Mug Press.</p>
              <div class="d-flex justify-content-between align-items-center">
               <div class="btn-group">
                  <button type="button" class="btn btn btn-outline-secondary">More detail</button>
                  <button type="button" class="btn btn btn-outline-secondary">Book a machine</button>
                </div>
              </div>
            </div>
          </div>
        </div>
       <div class="col">
          <div class="card shadow-sm">
            <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
            <div class="card-body">
              <p class="card-text">Description for Electronics components and Tools.</p>
              <div class="d-flex justify-content-between align-items-center">
               <div class="btn-group">
                  <button type="button" class="btn btn btn-outline-secondary">More detail</button>
                  <button type="button" class="btn btn btn-outline-secondary">Book a machine</button>
                </div>
              </div>
            </div>
          </div>
        </div>
       <div class="col">
          <div class="card shadow-sm">
            <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
            <div class="card-body">
              <p class="card-text">Description for Power and Hand Tools.</p>
              <div class="d-flex justify-content-between align-items-center">
               <div class="btn-group">
                  <button type="button" class="btn btn btn-outline-secondary">More detail</button>
                  <button type="button" class="btn btn btn-outline-secondary">Book a machine</button>
                </div>
              </div>
            </div>
          </div>
        </div>

</main>

{% endblock %}

fablab/templates/fablab/user_booking.html
{% extends "fablab/base.html" %}

{% block content %}

    <div class="container">

        <div style="height: 100px;">
            <div class="h-25 text-center"><h1>{{ user.firstName}} {{user.surName }}</h1></div>
        </div>

        <div class="row">
            <div class="col">
                Date
            </div>
            <div class="col">
                Start time
            </div>
            <div class="col">
                End time
            </div>
        </div>

        {% if userBooking %}
            {% for booking in userBooking %}
                <div class="row">
                <div class="col">
                    {{booking.slotDate}}
                </div>
                <div class="col">
                    {{booking.slotStatTime}}
                </div>
                <div class="col">
                    {{booking.slotEndTime}}
                </div>
            </div>
            {% endfor %}
        {% else %}
            <p> No booking available. </p>
        {% endif %}

    </div>

{% endblock %}

fablab/templates/fablab/users.html
{% extends "fablab/base.html" %}

{% block content %}

    <div class="container">

        <div style="height: 100px;">
            <div class="h-25 text-center"><h1>Fablab Jerez El Altillo School</h1></div>
        </div>
        <div class="row">
            <div class="col">
                User ID
            </div>
            <div class="col">
                Full Name
            </div>
            <div class="col">
                Email
            </div>
        </div>

        {% if users_list %}
            {% for user in users_list %}
                <div class="row">
                <div class="col">
                    {{user.id}}
                </div>
                <div class="col">
                    <a href="{% url 'fablab:userbooking' user.id %}">{{user.firstName}} {{user.surName}} Checking</a>
                </div>
                <div class="col">
                    {{user.email}}
                </div>
            </div>
            {% endfor %}
        {% else %}
            <p> No polls are available. </p>
        {% endif %}

    </div>

{% endblock %}